### ISSUE TITLE
nc need -p flag on debian 7

### ISSUE THREAD

**Issue by sebraison** [Neilpang/le#95] opened 2016-03-10 17:06 UTC
Hello,

when using in stand alone mode le.sh spawn a nc process with the command "nc -q 1 -l 80". At least on my debian version (7.9 up to date) nc needs the -p flag in order to listen on port 80.

It can be fixed on lines 348 and 350 of le.sh

Thank you for your work.

Best regards,

SR.

**Comment by Neilpang** [comment] 2016-03-11 14:24
sorry,  it was caused by my last fix for https://github.com/Neilpang/le/issues/88

It's fixed now.

**Closed** 2016-03-13 03:42 UTC
